news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.IndexView.as_view(), name='news_list'),
    path('my/', views.MyNewsListView.as_view(), name='my_news_list'),
    path('moderate_list/', views.ModerateNewsListView.as_view(), name='moderate_list'),
    path('search/', views.search_view, name='search'),
    path('admit/<int:pk>/', views.admit_view, name='admit'),
    path('admit_comment/<int:pk>/', views.admit_comment_view, name='admit_comment'),
    path('create/', views.CreateNews.as_view(), name='create'),
    path('<int:pk>/detail/', views.DetailView.as_view(), name='detail'),
    path('new_comment/', views.new_comment_view, name='new_comment')
]

newsSite/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', lambda request: redirect(reverse('news:news_list'), permanent=False)),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class News(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    photo = models.ImageField(upload_to='news', null=True, blank=True)
    create_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE, default=None, null=True)
    admitted = models.BooleanField(default=False, verbose_name='Допущено')

    def __str__(self):
        return self.title + ' ' + str(self.create_date)

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    def was_created_recently(self):
        now = timezone.now()
        return now >= self.create_date >= now - datetime.timedelta(days=1)


class Comment(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    create_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True)
    admitted = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

news/forms.py
from django import forms
from django.forms import Textarea

from news.models import News


class NewCommentForm(forms.Form):
    news_id = forms.IntegerField(required=False)
    new_comment = forms.CharField(label='Новый комментарий', max_length=100)

news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.views.generic import CreateView, FormView

from .models import News, Comment
from .forms import NewCommentForm


def new_comment_view(request):
    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            news_id = form.cleaned_data['news_id']
            text = form.cleaned_data['new_comment']
            author = None
            if not request.user.is_anonymous:
                author = request.user

            Comment.objects.create(text=text, news_id=news_id, author=author)
            return redirect(reverse('news:detail', args=(news_id,)))
        else:
            return HttpResponse("form is not valid")
    else:
        return HttpResponse("Сюда нельзя запросом не post")


def search_view(request):
    value = request.GET.get('search_query', '')
    news = News.objects.filter(create_date__lte=timezone.now()).filter(title__icontains=value).filter(admitted=True).order_by('-create_date')
    context = {
        'page_title': 'Результат поиска "' + str(value) + '" в названиях новостей',
        'news_list': news,
    }
    return render(request, 'news/index.html', context)


class ModerateNewsListView(LoginRequiredMixin, generic.ListView):
    paginate_by = 5
    template_name = 'news/index.html'

    def get_queryset(self):
        return News.objects.filter(create_date__lte=timezone.now()).filter(admitted=False).order_by('-create_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Новости для модерации'
        context['moderate_page'] = True
        return context


class MyNewsListView(LoginRequiredMixin, generic.ListView):
    paginate_by = 5
    template_name = 'news/index.html'

    def get_queryset(self):
        return News.objects.filter(create_date__lte=timezone.now()).filter(author=self.request.user).order_by(
            '-create_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Мои новости'
        return context


class IndexView(generic.ListView):
    paginate_by = 5
    template_name = 'news/index.html'

    def get_queryset(self):
        return News.objects.filter(create_date__lte=timezone.now()).filter(admitted=True).order_by('-create_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Опубликованные новости'
        return context


class DetailView(generic.DetailView):
    model = News
    template_name = 'news/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = NewCommentForm()
        context['comment_list'] = context['news'].comment_set.order_by('-create_date')
        return context

    def get_queryset(self):
        return News.objects.filter(create_date__lte=timezone.now())


class CreateNews(LoginRequiredMixin, CreateView):
    success_url = reverse_lazy('news:news_list')
    template_name = 'news/create.html'
    model = News
    fields = ['title', 'text', 'photo', 'author']

    def get_form(self, form_class=None):
        form = super().get_form()
        form.fields['author'].required = False
        return form

    def form_valid(self, form):
        news = form.save(commit=False)
        news.author = self.request.user
        return super().form_valid(form)


def admit_view(request, pk):
    news = News.objects.get(pk=pk)
    news.admitted = True
    news.save()
    return redirect(reverse('news:moderate_list'))


def admit_comment_view(request, pk):
    comment = Comment.objects.get(pk=pk)
    comment.admitted = True
    comment.save()
    return redirect(request.META.get('HTTP_REFERER'))

news/templates/news/base.html
{% block base %}
    {% load static %}
    <html>
        <head>
            <link rel="stylesheet" type="text/css" href="/{% static '/news/style.css' %}">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
                  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                    crossorigin="anonymous"></script>
        </head>
    <body>
        <nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
            <div class="container-fluid">
                <a class="navbar-brand" href="/news">Новости</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02"
                        aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample02">
                    <ul class="navbar-nav me-auto">
                        {#          <li class="nav-item">#}
                        {#            <a class="nav-link active" aria-current="page" href="#">Home</a>#}
                        {#          </li>#}
                        {#          <li class="nav-item">#}
                        {#            <a class="nav-link" href="#">Link</a>#}
                        {#          </li>#}
                    </ul>
                    {#        <form>#}
                    {#          <input class="form-control" type="text" placeholder="Search" aria-label="Search">#}
                    {#        </form>#}
                </div>
            </div>
        </nav>
        <div class="container py-5">
            {% block content %}
            {% endblock %}
        </div>
    </body>


    </html>
{% endblock %}

news/templates/news/create.html
{% extends 'base.html' %}

{% block content %}
    <h3>Создание новости</h3>
    <form action="{% url 'news:create' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <label for="title">Заголовок</label>
        <p>{{ form.title }}</p>
        <label for="photo">Фото</label>
        <p>{{ form.photo }}</p>
        <label for="text">Текст</label>
        <p>{{ form.text }}</p>
        <div class="d-none">{{ form.author }}</div>
        {{ form.non_field_errors }}

        {#                {{ form.as_p  }}#}
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

news/templates/news/detail.html
{% extends 'base.html' %}
{% load news_site_tags %}
{% load static %}

{% block content %}
    {% if news %}

        <head>
            <link rel="stylesheet" type="text/css" href="{% static 'news/css/style.css' %}">
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            {#            <script src="https://html2canvas.hertzen.com/dist/html2canvas.js"></script>#}
            {#            <script src="https://mrrio.github.io/jsPDF/dist/jspdf.debug.js"></script>#}
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>

            <script src="{% static '/news/js/html2canvas.js' %}"></script>
            {#            <script src="{% static '/jspdf.min.js' %}"></script>#}

        </head>

        <script type="module">

        </script>

        <script type="module">

            let news = document.querySelector('#news')

            html2canvas(news,
                {
                    backgroundColor: '#FFFFFF',
                    background: "#fafafa",
                    width: 595,
                    height: 842,
                }).then(canvas => {
                let pdf = new jsPDF('p', 'pt', 'letter');
                pdf.addImage(canvas, 'JPEG', 10, 10, 595, 842, '');
                let savePdfBtn = document.getElementById('savePdfBtn')

                savePdfBtn.onclick = function savePDF() {
                    pdf.save('{{ news.title }}' + '.pdf');
                }
            });


        </script>

        {% if not news.admitted and user|has_group:"moderators" %}
            <a class="btn btn-success text-light" href="{% url 'news:admit' news.id %}">Опубликовать новость</a>
        {% endif %}

        <div id="news">
            <h3 id="news-title">{{ news.title|upper }}</h3><br>
            {% if news.photo %}
                <img id="news-photo" height="400px" src="{{ news.photo.url }}"><br>
            {% endif %}
            <p id="news-text">{{ news.text }}</p>
            <span class="fw-bold">Автор: {{ news.author }}</span>
        </div>
        <div id="editor"></div>
        <a type="button" class="btn btn-danger text-light" id="savePdfBtn">Скачать PDF</a>
        <div class="container py-5">
            <h3>Комментарии</h3>
            <div class="container py-5">
                <form action="{% url 'news:new_comment' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="news_id" required="" id="id_news_id" value={{ news.id }}>
                    <input type="text" name="new_comment" maxlength="100" required="" id="id_new_comment">
                    {#                        {{ form }}#}
                    <input type="submit" value="Отправить на проверку">
                </form>
            </div>

            <div class="container py-5">
                {% for comment in comment_list %}
                    {% if comment.admitted or comment.author == user or user|has_group:"moderators" %}
                        <div class="row">
                            <div class="col">
                                {% if comment.author %}
                                    <span>{{ comment.author }}</span>
                                {% else %}
                                    <span>Гость</span>
                                {% endif %}
                                {% if not user.is_anonymous and comment.author == user and not comment.admitted %}
                                    <span class="text-danger">(Не проверено модерацией)</span>
                                {% endif %}
                                {% if not comment.admitted and user|has_group:"moderators" %}
                                    <a class="btn btn-success text-light"
                                       href="{% url 'news:admit_comment' comment.id %}">Опубликовать</a>
                                {% endif %}
                                <p class="ms-4">{{ comment.text }}</p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

news/templates/news/index.html
{% extends 'base.html' %}

{% block content %}
    {% if page_title %}
        <h3>{{ page_title }}</h3>
    {% endif %}
    {% if news_list  %}
        <div class="container-fluid py-3">
        {% for news in news_list  %}
            <div class="row py-1">
                <div class="col news-link">
                    {% if moderate_page  %}
                        <a class="btn btn-success text-light" href="{% url 'news:admit' news.id%}">Опубликовать</a>
                    {% endif %}
                    <a class=" text-decoration-none fw-bold font-size-lg" href="{% url 'news:detail' news.id %}">{{ news.title }}</a>
                </div>
            </div>
        {% endfor %}
        </div>
        <div class="pagination pt-5">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">пред</a>
                {% endif %}

                <span class="current">
                        Стр {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">след</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">конец &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        No news are available now
    {% endif %}
{% endblock %}

news/templates/news/thanks.html
{% extends 'base.html' %}

{% block content %}
    <h1>Спасибо!</h1>
    {% if text %}
        {{ text }}
    {% endif %}
{% endblock %}