news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.IndexView.as_view(), name='news_list'),
    path('my/', views.MyNewsListView.as_view(), name='my_news_list'),
    path('moderate_list/', views.ModerateNewsListView.as_view(), name='moderate_list'),
    path('search/', views.search_view, name='search'),
    path('admit/<int:pk>/', views.admit_view, name='admit'),
    path('admit_comment/<int:pk>/', views.admit_comment_view, name='admit_comment'),
    path('create/', views.CreateNews.as_view(), name='create'),
    path('<int:pk>/detail/', views.DetailView.as_view(), name='detail'),
    path('new_comment/', views.new_comment_view, name='new_comment')
]

newsSite/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', lambda request: redirect(reverse('news:news_list'), permanent=False)),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('reg/', views.SignUpView.as_view(), name='signup'),
    path('toggle_group/<str:group_name>', views.toggle_group, name='toggle_group'),
]

templates/base.html
{% block base %}
    {% load static %}
    {% load news_site_tags %}
    <html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">

{#        <script src="{% static "news/js/bootstrap.min.js" %}"></script>#}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                crossorigin="anonymous"></script>
    </head>
    <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
        <div class="container-fluid">
            <a class="navbar-brand" href="/news">Новости</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02"
                    aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample">
                <ul class="navbar-nav me-auto">
                    {% if request.user|has_group:"authors" %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'news:create' %}">Создать
                                новость</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'news:my_news_list' %}">Мои
                                новости</a>
                        </li>
                        {#                    {% else %}#}
                        {#                        {% if user.is_authenticated %}#}
                        {#                            <li class="nav-item">#}
                        {#                                <a class="nav-link active" aria-current="page" href="">Пользователь - не автор</a>#}
                        {#                            </li>#}
                        {#                        {% endif %}#}
                    {% endif %}
                    {% if request.user|has_group:"moderators" %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'news:moderate_list' %}">Новости
                                для модерации</a>
                        </li>
                    {% endif %}
                </ul>

                <div class="mx-1">
                    {% if user|has_group:"authors" %}
                        <span class="text-success"> Автор </span>
                    {% else %}
                        <span class="text-danger"> Не автор </span>
                    {% endif %}
                </div>

                <div class="mx-1">
                    {% if user|has_group:"moderators" %}
                        <span class="text-success"> Модератор </span>
                    {% else %}
                        <span class="text-danger"> Не модератор </span>
                    {% endif %}
                </div>

                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle me-1" type="button"
                                id="dropdownMenuButton1"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" href="{% url 'users:toggle_group' 'authors' %}">Изменить роль
                                Автор</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:toggle_group' 'moderators' %}">Изменить
                                роль Модератор</a></li>
                            <li><a class="dropdown-item text-danger" href="{% url 'users:logout' %}">Выйти</a></li>
                        </ul>
                    </div>
                {% else %}
                    <a class="btn btn-success mx-1" href="{% url 'users:signup' %}">Зарегистрироваться</a>
                    <a class="btn btn-secondary mx-1" href="{% url 'users:login' %}">Войти</a>
                {% endif %}
                <form action="{% url 'news:search' %}" class="navbar-nav form-inline mt-md-0", method="get">
                    <input id="search_query" name="search_query" class="form-control mr-sm-2" type="text" placeholder="Название статьи" aria-label="Search">
                    <button class="btn btn-outline-success ms-1 my-sm-0" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container py-5">
        {% block content %}
        {% endblock %}
    </div>
    </body>


    </html>
{% endblock %}